List<String> animeList = {
  "Naruto: Shippuden",
  "One Piece",
  "Attack on Titan",
  "My Hero Academia",
  "Black Clover",
  "Demon Slayer",
  "Jujutsu Kaisen",
  "Tokyo Revengers",
  "Chainsaw Man",
  "Boruto: Naruto Next Generations",
  "Hunter x Hunter",
  "Fullmetal Alchemist: Brotherhood",
  "Death Note",
  "One Punch Man",
  "Dragon Ball Z",
}.toList();